### ISSUE TITLE
todo feature of GUI

### ISSUE THREAD

**Issue by Tatsumi00** [EricYsh/riscgame#28]
- [ ] windows closing
- [ ] set up blank territory according to number of clients
- [ ] change color of territory according to the owner
- [ ] combine boardtextview with GUI together
@Astrosike @Tatsumi00
